### ISSUE TITLE
"invalid type: null, expected a string" when fetching an email

### ISSUE THREAD

**Issue by rbaumier** [resend/resend-rust#11]
Hello, 
Thanks for the library! 

I've encountered the following error when fetching an email using `client.emails.get()`:
```
thread 'main' panicked at src/main.rs:11:10:
called `Result::unwrap()` on an `Err` value: Http(reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a sequence", line: 1, column: 285) })
```

The error comes from trying to deserialize the email into the [Email](https://github.com/resend/resend-rust/blob/main/src/emails.rs#L356) struct:
- `bcc` can be `null`, yet a `Vec` is expected
- `cc` can be `null`, yet a `Vec` is expected
- `text` can be `null`, yet a `String` is expected

Here is a minimal reproductive example:

```toml
[package]
name = "repro"
version = "0.1.0"
authors = [""]
edition = "2021"

[dependencies]
resend-rs = "0.8.0"
serde = "1.0.204"
serde_json = "1.0.120"
serde_path_to_error = "0.1.16"
tokio = { version = "1", features = ["full"] }
```

```rust
use resend_rs::types::Email;

#[tokio::main]
async fn main() {
    let email = r#"{
        "object": "email",
        "id": "6757a66c-3a5b-49ee-98cc-fca7a5f423c0",
        "to": [
            "email@gmail.com"
        ],
        "from": "email@gmail.com>",
        "created_at": "2024-07-11 07:49:53.682607+00",
        "subject": "Subject",
        "bcc": null,
        "cc": null,
        "reply_to": null,
        "last_event": "delivered",
        "html": "<div></div>",
        "text": null
    }"#;

    let jd = &mut serde_json::Deserializer::from_str(email);
    let result: Result<Email, _> = serde_path_to_error::deserialize(jd);
    result.unwrap();
}
```

Running the code gives us the following error:
```
thread 'main' panicked at src/main.rs:24:12:
called `Result::unwrap()` on an `Err` value: Error { path: Path { segments: [Map { key: "bcc" }] }, original: Error("invalid type: null, expected a sequence", line: 10, column: 19) }
```
